### ISSUE TITLE
search results page (milestone #2)

### ISSUE THREAD

**Issue by campustradein** [campustradein/front-end#7]
- [ ] navar at the top
- [ ] search bar underneath
- [ ] sort by price, user rating etc to the left similar to this:
  ![image](https://cloud.githubusercontent.com/assets/19155331/16085085/9010ce36-32e0-11e6-92d7-37c60b046f2f.png)
- [ ] Search item includes: a book cover image, book name, author, isbn number, date listed, user that listed it and price

This is the idea but not how it should look. It should look way prettier than this
![image](https://cloud.githubusercontent.com/assets/19155331/16084953/21763240-32e0-11e6-81f8-8c9db39766f6.png)
